from .asociacion import Asociacion
from .contrato_club import ContratoClub
from .serie import Serie
from .solicitud import Solicitud
from .historial_serie import HistorialSerie
from .rol import Rol
from .archivo import Archivo
from .entrenamiento import Entrenamiento
from .permiso_rol import PermisoRol
from .estadisticas_jugador import EstadisticasJugador
from .ficha_jugador import FichaJugador
from .evaluacion_fisica import EvaluacionFisica
from .pais import Pais
from .reunion import Reunion
from .historial_ingreso import Historial_ingreso
from .historial_egreso import Historial_egreso
from .castigo import Castigo
from .cancha import Cancha
from .calendario import Calendario
from .asistencia_reunion import AsistenciaReunion
from .cuenta_usuario import CuentaUsuario
from .historial_permiso import HistorialPermiso
from .usuario import Usuario
from .club import Club
from .orden_pago import OrdenPago
from .permiso import Permiso
